sudo: required
services:
  - docker
before_install:
  - docker build -t 15ee35013/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true 15ee35013/react-test npm test -- --coverage

after_success:
  - docker build -t 15ee35013/multi-client ./client
  - docker build -t 15ee35013/multi-nginx ./nginx
  - docker build -t 15ee35013/multi-server ./server
  - docker build -t 15ee35013/multi-worker ./worker
  #Log In
  - echo "$Docker_pass" | docker login -u "$Docker_Id" --password-stdin
  #Take and push to docker hub online 
  - docker push 15ee35013/multi-client
  - docker push 15ee35013/multi-nginx
  - docker push 15ee35013/multi-server
  - docker push 15ee35013/multi-worker



